/*****************************************/
/**   Author : Ahmed Ashraf				*/
/**   DATE   : 22 OCT 2020              */
/**   Version: V01						*/
/****************************************/
#ifndef		TIMER1_CONFIG_H
#define     TIMER1_CONFIG_H

/*************************************************************************************************/
/****  <-----  MODE OF OPERATION		--->													*/
/*
//////////UPDATED MEAN OCRA1x Updated when
Options : 
TIMER1_NORMAL_0xFFFF_TOP_UPDATED_IMMEDIATE			
TIMER1_PHASE_CORRECT_PWM_0x00FF_TOP_UPDATED_TOP		
TIMER1_PHASE_CORRECT_PWM_0x01FF_TOP_UPDATED_TOP		
TIMER1_PHASE_CORRECT_PWM_0x03FF_TOP_UPDATED_TOP		
TIMER1_CTC_OCR1A_TOP_UPDATED_IMMEDIATE				
TIMER1_FAST_PWM_0x00FF_TOP_UPDATED_TOP				
TIMER1_FAST_PWM_0x01FF_TOP_UPDATED_TOP				
TIMER1_FAST_PWM_0x03FF_TOP_UPDATED_TOP				
TIMER1_PHASE_CORRECT_PWM_ICR1_TOP_UPDATED_BOTTOM	
TIMER1_PHASE_CORRECT_PWM_OCR1A_TOP_UPDATED_BOTTOM	
TIMER1_PHASE_CORRECT_PWM_ICR1_TOP_UPDATED_TOP		
TIMER1_PHASE_CORRECT_PWM_OCR1A_TOP_UPDATED_TOP		
TIMER1_CTC_MODE_ICR1_TOP_UPDATED_IMMEDIATE			
TIMER1_FAST_PWM_MODE_ICR1_TOP_UPDATED_TOP			
TIMER1_FAST_PWM_MODE_OCR1A_TOP_UPDATED_TOP			
*/
#define		TIMER1_MODE_OPERATION		TIMER1_FAST_PWM_MODE_ICR1_TOP_UPDATED_TOP
/************************************************************************************************/
/**** <----- TIMER PRESCALER	--->															*/
/*
TIMER FREQUENCY = 8MHZ /PRESCALER 
Options : 
TIMER1_COUNTER_STOPPED
TIMER1_NO_PRESCALLER
TIMER1_8_PRESCALER
TIMER1_64_PRESCALER
TIMER1_256_PRESCALER
TIMER1_1024_PRESCALER
TIMER1_EXTERNAL_CLOCK_ON_T0_PIN_FALLING_EDGE
TIMER1_EXTERNAL_CLOCK_ON_T0_PIN_RISING_EDGE
*/
#define TIMER1_CLOCK_SELECT										TIMER1_8_PRESCALER	

/**************************************************************************************************/	
/***  <---  OC1A PIN (PD5)	--->																*/
/*
Options :
//FOR NON_PWM (NORMAL && CTC)//
TIMER1_OC1A_NORMAL_PORT_OPERATION								  
TIMER1_OC1A_TOGGLE_ON_COMPARE_MATCH_NON_PWM						
TIMER1_OC1A_CLEAR_ON_COMPARE_MATCH_NON_PWM						
TIMER1_OC1A_SET_ON_COMPARE_MATCH_NON_PWM
//FOR FAST_PWM//			  
TIMER1_OC1A_CLEAR_ON_COMPARE_MATCH_SET_TOP_FAST_PWM				
TIMER1_OC1A_SET_ON_COMPARE_MATCH_CLEAR_TOP_FAST_PWM		
//FOR PHASA CORRECT	//	  
TIMER1_OC1A_CLEAR_ON_UP_COUNTING_SET_DOWN_COUNTING_PHASE_CORRECT
TIMER1_OC1A_SET_ON_UP_COUNTING_CLEAR_DOWN_COUNTING_PHASE_CORRECT
*/																  
#define		TIMER1_OC1A_MODE_OPERATION			TIMER1_OC1A_SET_ON_COMPARE_MATCH_CLEAR_TOP_FAST_PWM

/****   <---  OC1B PIN (PD4)	--->														*/
/*
Options :
//FOR NON_PWM (NORMAL && CTC)//
TIMER1_OC1B_NORMAL_PORT_OPERATION								  
TIMER1_OC1B_TOGGLE_ON_COMPARE_MATCH_NON_PWM						
TIMER1_OC1B_CLEAR_ON_COMPARE_MATCH_NON_PWM						
TIMER1_OC1B_SET_ON_COMPARE_MATCH_NON_PWM
//FOR FAST PWM//					  
TIMER1_OC1B_CLEAR_ON_COMPARE_MATCH_SET_TOP_FAST_PWM				
TIMER1_OC1B_SET_ON_COMPARE_MATCH_CLEAR_TOP_FAST_PWM		
//FOR PHASE CORRECT	//	  
TIMER1_OC1B_CLEAR_ON_UP_COUNTING_SET_DOWN_COUNTING_PHASE_CORRECT
TIMER1_OC1B_SET_ON_UP_COUNTING_CLEAR_DOWN_COUNTING_PHASE_CORRECT
*/																  
#define		TIMER1_OC1B_MODE_OPERATION			TIMER1_OC1B_NORMAL_PORT_OPERATION
/**********************************************************************************************/
/**********************************************************************************************/
/*FOR INPUT CAPTURE UNIT */
/*
Options : 
INPUT_CAPTURE_NOISE_CANCELER_ENABLE
INPUT_CAPTURE_NOISE_CANCELER_DISABLE

*/
#define INPUT_CAPTURE_NOISE_CANCELER			INPUT_CAPTURE_NOISE_CANCELER_ENABLE

/**********************************************************************************************
/*			<--------  TIMER1   INTERRUPT	--------------------------->									*/
/*
Options : 
TIMER1_INTERRUPT_ENABLE
TIMER1_INTERRUPT_DISABLE
*/
#define TIMER1_INTERRUPT_STATE									TIMER1_INTERRUPT_ENABLE	
/*
Options : 

TIMER1_INPUT_CAPTURE_INTERRUPT					
TIMER1_COMPARE_MATCH_A_INTERRUPT				
TIMER1_COMPARE_MATCH_B_INTERRUPT				
TIMER1_OVERFLOW_INTERRUPT_ENABLE				

TIMER1_INPUT_CABTURE_AND_COMPATE_MATCH_A        
TIMER1_INPUT_CABTURE_AND_COMPATE_MATCH_A_AND_B  
TIMER1_COMPATE_MATCH_A_AND_B          			

TIMER1_OVERFLOW_AND_COMPATE_MATCH_A        		
TIMER1_OVERFLOW_AND_COMPATE_MATCH_A_AND_B     	
*/


#define		TIMER1_INTERRUPT		TIMER1_INPUT_CAPTURE_INTERRUPT


#endif
